# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5e06d66fb87f690a2bab9759aa51ef631998c4b88eb6eb75b732c0efe5b63671eb0eb1d6cddd966db8234f9b08f302927ecb0f8401b6554f8c2e1abdb993ba5f

test:
  secret_key_base: da66b3231c7ba33e73ff13e4f85d70e5517aaf6cbf1a389704f141ace8229b21fe83dc8f7bbecf58cf70e3f359ef089cd3db72272b5dbc3814fbc3cb9e2937b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
